#!/usr/bin/env python                                                                                                                        
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import time
driver=webdriver.Chrome()
driver.get("https://vtop.vit.ac.in/vtop")
submit=driver.find_elements_by_xpath("//button[contains(text(),'Login to V-TOP')]")[0]
submit.click()
time.sleep(1)
username=driver.find_element_by_css_selector("#uname")
username.send_keys("{registration no}")
password=driver.find_element_by_css_selector("#passwd")
password.send_keys("{password}")
time.sleep(2)
driver.find_elements_by_xpath("//button[contains(text(),'Sign in')]")[0].click()

